### ISSUE TITLE
What does this theme still need before it can be submitted?

### ISSUE THREAD

**Issue by Anomalocaridid** [remiposo/swaylock#1]
I have been using this swaylock theme for a while and I really like it. I would like to help get this port ready to be submitted to the Catppuccin GitHub organization.

What does this theme still need before it can be submitted? Does it just need preview screenshots or are there other things to do as well?

**Comment by remiposo** [comment]
@Anomalocaridid 

Thanks for using!
I've created it for personal use, but I haven't been using Linux lately...
It seems that others are using it too, so I would like to submit it during the New Year's holiday. 

It's easy since it's just taking a screenshot.
Please wait a moment.

**Comment by remiposo** [comment]
@Anomalocaridid 
Thank you for helping me.
I created a issue for port review!
https://github.com/catppuccin/catppuccin/issues/2248

**Comment by Anomalocaridid** [comment]
@remiposo It was my pleasure! I'm glad I could help out with this.
